
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EMPTY LPAREN RPAREN EQUAL RANGE INTEGER FLOAT ID COMMA CREATE EARN LOSE REMOVE DISPLAY LENGTH COMBINE SUBSTRACT PW FW CFD\n    action : fuction_earn\n            | fuction_lose\n            | fuction_remove\n            | fuction_pw\n            | fuction_fw\n            | fuction_display\n            | fuction_length\n            | variable\n            | EMPTY\n\n    \n    fuction_earn : EARN LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN\n                | EARN LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN\n    \n    fuction_lose : LOSE LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN\n                | LOSE LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN\n    \n    fuction_remove : REMOVE LPAREN INTEGER COMMA ID RPAREN\n    \n    fuction_pw : PW LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN\n                | PW LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN\n    \n    fuction_fw : FW LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN\n                | FW LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN\n    \n    fuction_display : DISPLAY LPAREN ID RPAREN\n    \n    fuction_length : LENGTH LPAREN ID RPAREN\n    \n    variable_combine : COMBINE LPAREN ID COMMA ID RPAREN\n    \n    variable_substract : SUBSTRACT LPAREN ID COMMA ID RPAREN\n    \n    variable_create : CREATE LPAREN INTEGER RPAREN\n    \n    variable : CFD ID EQUAL variable_create\n                | CFD ID EQUAL variable_combine\n                | CFD ID EQUAL variable_substract\n\n\n    '
    
_lr_action_items = {'EMPTY':([0,],[10,]),'EARN':([0,],[11,]),'LOSE':([0,],[12,]),'REMOVE':([0,],[13,]),'PW':([0,],[14,]),'FW':([0,],[15,]),'DISPLAY':([0,],[16,]),'LENGTH':([0,],[17,]),'CFD':([0,],[18,]),'$end':([1,2,3,4,5,6,7,8,9,10,48,49,50,51,52,72,88,91,92,93,94,95,96,97,98,101,102,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-19,-20,-24,-25,-26,-14,-23,-10,-11,-12,-13,-15,-16,-17,-18,-21,-22,]),'LPAREN':([11,12,13,14,15,16,17,53,54,55,],[19,20,21,22,23,24,25,65,66,67,]),'ID':([18,24,25,43,66,67,68,69,70,71,73,74,75,76,89,90,],[26,36,37,60,78,79,80,81,82,83,84,85,86,87,99,100,]),'FLOAT':([19,20,22,23,],[27,29,32,34,]),'INTEGER':([19,20,21,22,23,39,40,41,42,44,45,46,47,65,],[28,30,31,33,35,56,57,58,59,61,62,63,64,77,]),'EQUAL':([26,],[38,]),'COMMA':([27,28,29,30,31,32,33,34,35,56,57,58,59,61,62,63,64,78,79,],[39,40,41,42,43,44,45,46,47,68,69,70,71,73,74,75,76,89,90,]),'RPAREN':([36,37,60,77,80,81,82,83,84,85,86,87,99,100,],[48,49,72,88,91,92,93,94,95,96,97,98,101,102,]),'CREATE':([38,],[53,]),'COMBINE':([38,],[54,]),'SUBSTRACT':([38,],[55,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'action':([0,],[1,]),'fuction_earn':([0,],[2,]),'fuction_lose':([0,],[3,]),'fuction_remove':([0,],[4,]),'fuction_pw':([0,],[5,]),'fuction_fw':([0,],[6,]),'fuction_display':([0,],[7,]),'fuction_length':([0,],[8,]),'variable':([0,],[9,]),'variable_create':([38,],[50,]),'variable_combine':([38,],[51,]),'variable_substract':([38,],[52,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> action","S'",1,None,None,None),
  ('action -> fuction_earn','action',1,'p_action','ECF_LEXER.py',100),
  ('action -> fuction_lose','action',1,'p_action','ECF_LEXER.py',101),
  ('action -> fuction_remove','action',1,'p_action','ECF_LEXER.py',102),
  ('action -> fuction_pw','action',1,'p_action','ECF_LEXER.py',103),
  ('action -> fuction_fw','action',1,'p_action','ECF_LEXER.py',104),
  ('action -> fuction_display','action',1,'p_action','ECF_LEXER.py',105),
  ('action -> fuction_length','action',1,'p_action','ECF_LEXER.py',106),
  ('action -> variable','action',1,'p_action','ECF_LEXER.py',107),
  ('action -> EMPTY','action',1,'p_action','ECF_LEXER.py',108),
  ('fuction_earn -> EARN LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN','fuction_earn',8,'p_fuction_earn','ECF_LEXER.py',115),
  ('fuction_earn -> EARN LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN','fuction_earn',8,'p_fuction_earn','ECF_LEXER.py',116),
  ('fuction_lose -> LOSE LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN','fuction_lose',8,'p_fuction_lose','ECF_LEXER.py',123),
  ('fuction_lose -> LOSE LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN','fuction_lose',8,'p_fuction_lose','ECF_LEXER.py',124),
  ('fuction_remove -> REMOVE LPAREN INTEGER COMMA ID RPAREN','fuction_remove',6,'p_fuction_remove','ECF_LEXER.py',131),
  ('fuction_pw -> PW LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN','fuction_pw',8,'p_fuction_pw','ECF_LEXER.py',138),
  ('fuction_pw -> PW LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN','fuction_pw',8,'p_fuction_pw','ECF_LEXER.py',139),
  ('fuction_fw -> FW LPAREN FLOAT COMMA INTEGER COMMA ID RPAREN','fuction_fw',8,'p_fuction_fw','ECF_LEXER.py',145),
  ('fuction_fw -> FW LPAREN INTEGER COMMA INTEGER COMMA ID RPAREN','fuction_fw',8,'p_fuction_fw','ECF_LEXER.py',146),
  ('fuction_display -> DISPLAY LPAREN ID RPAREN','fuction_display',4,'p_fuction_display','ECF_LEXER.py',152),
  ('fuction_length -> LENGTH LPAREN ID RPAREN','fuction_length',4,'p_fuction_length','ECF_LEXER.py',159),
  ('variable_combine -> COMBINE LPAREN ID COMMA ID RPAREN','variable_combine',6,'p_variable_combine','ECF_LEXER.py',167),
  ('variable_substract -> SUBSTRACT LPAREN ID COMMA ID RPAREN','variable_substract',6,'p_variable_substract','ECF_LEXER.py',173),
  ('variable_create -> CREATE LPAREN INTEGER RPAREN','variable_create',4,'p_variable_create','ECF_LEXER.py',179),
  ('variable -> CFD ID EQUAL variable_create','variable',4,'p_variable','ECF_LEXER.py',186),
  ('variable -> CFD ID EQUAL variable_combine','variable',4,'p_variable','ECF_LEXER.py',187),
  ('variable -> CFD ID EQUAL variable_substract','variable',4,'p_variable','ECF_LEXER.py',188),
]
